---
metadata:
  name: "disallow-test-tag"
  annotations:
    policies.kyverno.io/title: Demo
    policies.kyverno.io/category: Accenture-Demo-Policy
    policies.kyverno.io/severity: major
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: "The ':test' tag is mutable and can lead to\
      \ unexpected errors if the image changes.  A best practice is to use an immutable\
      \ tag (e.g. v2.3) that maps to a specific version  of an application pod."
apiVersion: "kyverno.io/v1"
kind: "ClusterPolicy"
spec:
  rules:
  - match:
      resources:
        kinds:
        - Pod
    name: require-image-tag
    validate:
      pattern:
        spec:
          containers:
          - image: "*:*"
      message: "An image tag is required."
  - match:
      resources:
        kinds:
        - Pod
    name: validate-image-tag
    validate:
      pattern:
        spec:
          containers:
          - image: "!*:test"
      message: "Using the ':test' tag is not recommended."
